[package]
name = "asi-rs"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
libc = "0.2"
env_logger = "0.9"
log = "0.4"
rfitsio = { git = "https://github.com/devducks/rfitsio", tag = "v0.2.0" }
num = "0.4"
astrotools = "0.3"
lightspeed-astro = "0.7"
tonic = "0.7"
tonic-reflection = "0.4"
tokio = { version = "1", features = ["rt-multi-thread", "signal"] }
convert_case = "0.5"
rand = "0.8"

[dependencies.uuid]
version = "1"
features = [
    "v4",
    "fast-rng",
]
